language: cpp
os: linux
dist: xenial
compiler:
  - gcc
services:
  - xvfb

env:
  global:
    - GCC_VERSION="9"

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    #Build dependencies:
    - cmake
    - p7zip-full
    - g++-9
    - gcc-9
    - cmake
    #SFML dependencies:
    - libopenal-dev
    - libjpeg-dev
    - libvorbis-dev
    - libflac-dev
    - libglew-dev
    - libudev-dev
    - libxrandr-dev
    - libsndfile1-dev
    - libglu1-mesa-dev
    - libfreetype6-dev
    - libx11-xcb-dev
    - libxcb-icccm4-dev
    - libxcb-image0
    - libxcb-image0-dev
    - libxcb-randr0-dev
    - libxcb-util0-dev
    - libxcb1-dev

install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-${GCC_VERSION}" CC="gcc-${GCC_VERSION}"; fi
- git clone https://github.com/SFML/SFML && cd SFML
- export SFML_ROOT=$(pwd)/build/install
- mkdir build && cd build
- cmake -DCMAKE_INSTALL_PREFIX=$(pwd)/install .. && make && make install && cd ../..
- git clone https://github.com/cristianglezm/JsonBox && cd JsonBox && mkdir build && cd build
- export JSONBOX_ROOT=$(pwd)/install
- cmake -DCMAKE_INSTALL_PREFIX=$JSONBOX_ROOT .. && make && make install && cd ../..

script:
- mkdir build && cd build
- cmake -DSFML_ROOT=$SFML_ROOT -DJSONBOX_ROOT=$JSONBOX_ROOT -DCMAKE_INSTALL_PREFIX=$(pwd)/install ..
- make
- make install
